import Link from 'next/link'

/**
 * Curated related links at the foot of a content page (Phase 4, Task 4.3).
 * Deliberately hand-picked per page rather than auto-generated by tag matching:
 * a tag matcher produces plausible-looking noise, and the whole point of these
 * links is that a human decided this is genuinely the next thing to read.
 */
export function RelatedReading({
  links,
  heading = 'Related reading',
}: {
  links: { label: string; href: string }[]
  heading?: string
}) {
  if (!links.length) return null
  return (
    <section className="max-w-[880px] mt-14">
      <div className="dim mb-6"><span>{heading}</span></div>
      <div className="grid gap-3 sm:grid-cols-2">
        {links.map((l) => (
          <Link
            key={l.href}
            href={l.href}
            className="plot-card px-5 py-4 hover:shadow-plot-hover transition-shadow group"
          >
            <span className="font-sans text-[15.5px] font-semibold group-hover:text-bronze transition-colors">
              {l.label} →
            </span>
          </Link>
        ))}
      </div>
    </section>
  )
}
